### ISSUE TITLE
why not use official FPDI?

### ISSUE THREAD

**Issue by michabbb** [hanneskod/libmergepdf#11]
https://github.com/Setasign/FPDI

**Comment by hanneskod** [comment]
Oh no reason. It just wasn't composerized when I wrote this library. I am glad they have gotten to it and you are right of course. Will update as soon as I get to it..

**Comment by garethellis36** [comment]
Hello @hanneskod any progress on this one?

I am using this library and it's very useful but I need to use the commercial version of FPDI and so far the only way I have to found to use it with your library is to copy-paste methods from \fpdi\fpdi_pdf_parser into a custom class which extends the commercial version. It works but it's quite brittle and liable to fail if one of the library updates at some point!

**Comment by garethellis36** [comment]
@hanneskod I just submitted PR #12 for this. HTH
