### ISSUE TITLE
The links in the pdfs aren't clickable after merging them

### ISSUE THREAD

**Issue by kovacs-tamas** [hanneskod/libmergepdf#14]
We have a problem with the merging tool. The first two pdfs are generated with dompdf, and they work well.

[aaa0.75641900 1472727705.pdf](https://github.com/hanneskod/libmergepdf/files/449460/aaa0.75641900.1472727705.pdf)
[aaa0.77990100 1472727705.pdf](https://github.com/hanneskod/libmergepdf/files/449459/aaa0.77990100.1472727705.pdf)

After merging them, the links are not clickable anymore.
[afinal.pdf](https://github.com/hanneskod/libmergepdf/files/449461/afinal.pdf)

**Comment by hanneskod** [comment]
This is due to how FPDI handles content and unfortunately nothing I can fix at this moment. Please see the link below..

https://www.setasign.com/support/faq/fpdi/after-importing-a-page-all-links-are-gone/#question-84
