### ISSUE TITLE
Erro with version PDF

### ISSUE THREAD

**Issue by RodrigoFraga** [hanneskod/libmergepdf#19]
Error: This document (xxx.pdf) probably uses a compression technique which is not supported by the free parser shipped with FPDI.

**Comment by hanneskod** [comment]
Hi and thanx for reporting. I am not sure I can help with this issue though. Seems to be related to FPDI.

See http://www.setasign.com/products/fpdi/about/

**Comment by hanneskod** [comment]
Closing as there has been no development...
