### ISSUE TITLE
Add unicode metadata

### ISSUE THREAD

**Issue by rudiedirkx** [hanneskod/libmergepdf#23]
After merging 2 PDF, all metadata is gone (title, subject, keywords etc). That's to be expected. I fixed that by adding metadata on the FPDI object:

```
$fpdi = new FPDI;
$merger = new Merger($fpdi);
$fpdi->SetTitle('Title Ś ś Ŝ ŝ Ş ş Ć ć Ĉ ĉ Ċ ċ Č č');
$merger->addRaw($raw);
```

etc. That works, but it doesn't seem to accept unicode. Is there a special way to add unicode metadata?

Proofs:

* Created PDF with DomPdf, without merging (works): https://webblocks.nl/tests/dompdf/pdf-nissewaard.php?nomerge
* Created PDF with DomPdf, and then merged with no other doc (doesn't work): https://webblocks.nl/tests/dompdf/pdf-nissewaard.php

**Comment by rudiedirkx** [comment]
`SetTitle` etc have a second argument `$isUtf8`. That's it. I'm blind.

**Comment by hanneskod** [comment]
Cool. Thanx for the follow up..
