### ISSUE TITLE
add Pages-Feature in method addFinder()

### ISSUE THREAD

**Issue by dennobaby** [hanneskod/libmergepdf#24]
It would be nice to use the function addFinder($finder) with an option for Pages().
Example:
  $m->addFinder($finder, new Pages('1'));

This would merge the first page of all found pdfs.

**Comment by hanneskod** [comment]
Yes why not. A simple edit. 

How about 0ef50257b9b3aac78c7576e7fa67c79a192cbdf3?

**Comment by dennobaby** [comment]
Yes, this looks good. I didn't check your Test accurately, but the call of addFromFile looks exaktly like my implementation, that works good! 

Nice too see that you maintain a repo that is used by not many people! You are a great help for people who create special solutions for special needs!

**Comment by hanneskod** [comment]
:) Thanx!
