### ISSUE TITLE
'Text File Busy' Exception

### ISSUE THREAD

**Issue by joydebnath** [hanneskod/libmergepdf#27]
I am trying to delete my pdf files after the merge. But it won't let me do it because the system is using the files. The reset function does not release those added files. How can I release those files?

**Comment by hanneskod** [comment]
Hi and thanx for reporting! I am unable to reproduce though. I also see that you closed the issue. Did you locate the problem?

**Comment by joydebnath** [comment]
Hi. Yes I have located the problem. It happens when I run the script in a job. I found out that even though the queue finished working, it did not release those files.

**Comment by hanneskod** [comment]
Ok. Thanx for the feedback!
