### ISSUE TITLE
Merging PDF files with v1.5 and newer not possible

### ISSUE THREAD

**Issue by NicoHaase** [hanneskod/libmergepdf#30]
Using the underlying FPDI library, merging files is not possible if one of them was created in PDF 1.5 or newer. Do you have any idea about how to solve this, eg. using another PDF library?

**Comment by kaystrobach** [comment]
We solved it using the commercial parser addon:

https://www.setasign.com/products/fpdi-pdf-parser/details/

**Comment by NicoHaase** [comment]
@kaystrobach, thanks for that hint, but as far as I see, a library like https://github.com/myokyawhtun/PDFMerger is told to be working with later PDF standards while staying free

**Comment by hanneskod** [comment]
Yes this is a limitation. Using `TCPDF` seams to be an option, but I guess that would need a little rewrite. I’ll try to get time to look at this..

**Comment by hanneskod** [comment]
There is a fix in master now, please try. It does however change the signature of `Merger::__construct()` so I am not able to release it in the 3.0 branch. Also there is a question if the version of TCPDI being used is currently maintained. Maybe this needs some additional thinking...

**Comment by kaystrobach** [comment]
sounds like a good plan

**Comment by NicoHaase** [comment]
A colleague of mine tested the change and reported that it's working: PDF files that could not be merged before could now :)

**Comment by kaystrobach** [comment]
@NicoHaase please provide a pull request.

**Comment by NicoHaase** [comment]
> @NicoHaase please provide a pull request.

I don't get that - @hanneskod as the maintainer of the project already implemented everything neccessary. For what do you need a PR?

**Comment by kaystrobach** [comment]
ahh sry, missed that comment

**Comment by hanneskod** [comment]
Thanx for the feedback!

I have released some updated as `4.0.0-beta1` today. To enable swapping backends 4.0 introduce the concept of `drivers`. The `fpdi` driver is still used by default and `tcpdi` is included as an option. I am still not a 100% satisfied with the version of tcpdi used, once everything is sorted tcpdi will probably be used as default.

For mor information see `CHANGELOG.md` and `README.md`.

Please open a new issue if you encounter any problems with the 4.0 branch. If I hear nothing I'll release a stable version in a week or so.
