### ISSUE TITLE
Merged PDF contains a line at the top

### ISSUE THREAD

**Issue by NicoHaase** [hanneskod/libmergepdf#32]
If I merge two PDF files using the latest v4.0 beta, all pages have a line drawn at their top. See the attached files for details.

What I've tried:
- this happens both with FPDF and TCPDI
- this happens with multiple PDF versions, not only with those that you could not use before

[merged.pdf](https://github.com/hanneskod/libmergepdf/files/2584690/merged.pdf)
[test.pdf](https://github.com/hanneskod/libmergepdf/files/2584688/test.pdf)

**Comment by hanneskod** [comment]
Oh. That’s weird. Must be a tcpdf thing. 3.* used fpdf behind fpdi, 4.* use tcpdf behind both fpdi and tcpdi.

(The relationships between fpdf, tcpdf, fpdi and tcpdi are really complex...)

I’ll look into it!

**Comment by hanneskod** [comment]
Some hints.

https://stackoverflow.com/questions/7950493/php-tcpdf-remove-headers-bottom-border

https://stackoverflow.com/questions/10601353/how-to-remove-line-below-header-and-above-html-in-tcpdf

But it’s not perfect. Header can be disabled, but what happens if merged PDFs contains headers??

**Comment by NicoHaase** [comment]
Thanks for providing the proper terms, that makes it easier to search for alternatives! https://stackoverflow.com/a/15981733/1116230 looks okay to me.

Otherwise: what exactly could break if you would disable the header through `SetPrintHeader`? Would this remove content that was present in the source files, but is no longer in the merged file?

**Comment by NicoHaase** [comment]
Hehe, you got me once more :) So, completely disabling header and footer looks like the best solution to me.

**Comment by hanneskod** [comment]
I did some testing, and as far as I can see disabling header and footer does not remove header or footer from source files when merging. Fix in master released as `4.0.0-beta2`. Can you validate that it works for you?

**Comment by NicoHaase** [comment]
Yes, it does work :) Thanks for your quick responses!
