### ISSUE TITLE
Warning: Ambiguous class resolution, "FPDF"

### ISSUE THREAD

**Issue by stenas** [hanneskod/libmergepdf#36]
Hello,

When I updated the package to version 4.0 the composer send this message

"Warning: Ambiguous class resolution, "FPDF" was found in both "....vendor/rafikhaceb/tcpdi/tcpdi.php" and ".....vendor/setasign/fpdf/fpdf.php", the first will be used."

The dependencies have two class with the same name FPDF.

Is it normal?

**Comment by hanneskod** [comment]
Hi and thanx for reporting!
I suspect this happens because you require `setasign/fpdf` in your `composer.json`. With 4.0 this is actually a conflict. Patching now to make this conflict explicit..

**Comment by hanneskod** [comment]
Can you validate that everything works as expected once `setasign/fpdf` is removed from the list of dependencies?

**Comment by hanneskod** [comment]
Closing, presumed fixed.
