### ISSUE TITLE
Problem with PDFs from DeutscheBahn

### ISSUE THREAD

**Issue by kaystrobach** [hanneskod/libmergepdf#38]
They use v1.5 pdfs:

![grafik](https://user-images.githubusercontent.com/1185776/62877811-20508480-bd28-11e9-83ed-0fb245d1dcf4.png)

We use code like this to add the documents:

```php
$merger = new Merger(new TcpdiDriver());
        foreach ($booking->getManuallyCreatedDocuments() as $manuallyCreatedDocument) {
            $merger->addRaw(
                stream_get_contents($manuallyCreatedDocument->getOriginalResource()->getStream())
            );
        }
```

What i get is: 'TCPDI_PARSER ERROR [tcpdi-5d5182b965944]: Pagenumber is wrong! (Requested 0, max )'

If i enable full exception handling i get the following error message:

[500 Internal Server Error.pdf.pdf](https://github.com/hanneskod/libmergepdf/files/3493332/500.Internal.Server.Error.pdf.pdf)

Would be nice to get an idea how to fix that - current workaround is to skip all documents, where the pagenumber can not be read from.

I would sponsor a fix, if you contact me and we negotiate the conditions.

**Comment by kaystrobach** [comment]
Workaround:

```php
        /** @var ManuallyCreatedDocument $manuallyCreatedDocument */
        foreach ($booking->getManuallyCreatedDocuments() as $manuallyCreatedDocument) {
            if ($this->getPageCount($manuallyCreatedDocument->getOriginalResource()->getStream()) > 0) {
                $merger->addRaw(
                    stream_get_contents($manuallyCreatedDocument->getOriginalResource()->getStream())
                );
            } else {
                $pdf= new \FPDF();
                $pdf->AddPage('P');
                $pdf->Write(5,'Fehler beim Einbinden:');
                $pdf->Write(5, $manuallyCreatedDocument->getTitle());
                $pdf->Write(5, $manuallyCreatedDocument->getOriginalResource()->getFilename());
                $merger->addRaw(
                    $pdf->Output('whatever', 'S')
                );
            }
        }
```

```php
    protected function getPageCount($stream): int
    {
        try {
            $tcpdi = new \TCPDI();
            return $tcpdi->setSourceData(stream_get_contents($stream));
        } catch (\Exception $exception) {
            return 0;
        }
    }
```

**Comment by hanneskod** [comment]
Hi and sorry for the late reply. I dont think i can help you though. My pdf-foo is actually weak. This lib is nothing more then a wrapper around fpdi. The tcpdi thing is a workaround for pdf 1.5. But the thing is that no one seams to be maintaining tcpdi. There are multiple forks with various functionality. But you need to study the pdf format to fix any issue. And thats not me...

If you know of any other open source lib with this kind of functionality i am glad to write a driver for it. I have been unable to find a suitable candidate...

**Comment by kaystrobach** [comment]
let's close it for now, thank you.
