### ISSUE TITLE
"Unable to find startxref" when fetching PDF via PHP

### ISSUE THREAD

**Issue by oliran** [hanneskod/libmergepdf#39]
Instead of calling a PDF file directly, I am loading it with a PHP script. If I navigate with browser directly to script "pdf_fetch.php" the PDF downloads correctly. But when I try:

`$merger->addFile('pdf_fetch.php');`

I get "TCPDI_PARSER ERROR Unable to find startxref". I'm not sure if I need to adjust the headers in some way. Currently I have:

`header("Content-Type: application/pdf");
header("Content-Disposition: attachment; filename='file.pdf'");`

**Comment by hanneskod** [comment]
If you are sending headers you are working with http content. This is a library for merging pdf content. You need access to the pdf to merge.
