### ISSUE TITLE
file marge error

### ISSUE THREAD

**Issue by thakor-maheshkumar** [hanneskod/libmergepdf#44]
I have added marge file using your package and barryvdh/laravel-dompdf but error like that.

![Screenshot_1](https://user-images.githubusercontent.com/53993063/77542063-9f678700-6ecb-11ea-83e9-e06ee9793d32.png)

**Comment by kaystrobach** [comment]
see #38 for the ability to detect the problem, you can catch the exception. i think you use a non supported pdf version. feel free to close if related to #38

**Comment by kaystrobach** [comment]
please check if your error is related to the one in #44 if not please provide the file and reopen the ticket.
