### ISSUE TITLE
Compress function

### ISSUE THREAD

**Issue by urbanogilson** [hanneskod/libmergepdf#46]
Is there a way to compress the .pdf file?

**Comment by kaystrobach** [comment]
sure you can always use gzip, zip or any other compression programm.

for php you can use https://www.php.net/manual/de/book.zip.php

**Comment by hanneskod** [comment]
There is no native support for compression in this lib, if that is what you are asking. You will need to look at other pdf sollutions for that. Hope you find what you are looking for.
