### ISSUE TITLE
coposer warning because of abandoned setasign/fpdi-fpdf 

### ISSUE THREAD

**Issue by SimonHeimberg** [hanneskod/libmergepdf#48]
**Describe the bug**

When installing this package, composer reports a warning:
```
Package setasign/fpdi-fpdf is abandoned, you should avoid using it. No replacement was suggested.
```

Not sure how to solve this best. Find an alternative. Adopt fpdi-fpdf? Inline the important parts?

**To Reproduce**

run `composer install` in this project, or in a project using libmergepdf

**Include files**

--

**Screenshots**

--

**Please complete the following information:**
 - PHP-version: 7.2
 - Version of library: iio/libmergepdf  3.1.1

**Additional context**

--

**Comment by SimonHeimberg** [comment]
The dependency was changed already. I did not properly check the current composer.json. Thanks for maintaining!

**Comment by hanneskod** [comment]
:+1:
